version: "3"

services:
  auth:
    container_name: johnjud-auth
    restart: unless-stopped
    build: .
    ports:
      - 3002:3002
    environment:
      - APP_PORT=3004
      - APP_ENV=development
      - APP_SECRET=secret
      - DB_URL=postgres://root:root@johnjud-local-db:5432/johnjud_db
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=3600
      - JWT_REFRESH_TOKEN_TTL=604800
      - JWT_ISSUER=issuer
      - JWT_RESET_TOKEN_TTL=900
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - AUTH_CLIENT_URL=http://localhost:3000
      - SENDGRID_API_KEY=api_key
      - SENDGRID_NAME=johnjud
      - SENDGRID_ADDRESS=johnjud@gmail.com
    networks:
      - johnjud

  local-db:
    image: postgres:15.1-alpine3.17
    container_name: johnjud-local-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: johnjud_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - johnjud

  cache:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - johnjud

volumes:
  postgres:
networks:
  johnjud: