version: "3"

services:
  local-db:
    image: postgres:15.1-alpine3.17
    container_name: johnjud-local-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: johnjud_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  postgres: