app:
  port: 3002
  debug: true
  secret: <secret>

database:
  host: localhost
  port: 5432
  name: johnjud_db
  username: root
  password: root

jwt:
  secret: <secret>
  expires_in: 3600
  refresh_token_ttl: 604800
  issuer: <issuer>
  reset_token_ttl: 900

redis:
  host: localhost
  port: 6379
  password: ""

auth:
  client_url: localhost:3000

sendgrid:
  api_key: <api_key>
  name: johnjud
  address: johnjud@gmail.com