app:
  port: 8081
  debug: true
  secret: <secret>

database:
  host: localhost
  port: 5432
  name: johnjud-auth-db
  username: root
  password: root

jwt:
  secret: <secret>
  expires_in: 3600
  issuer: <issuer>