name: "Build and Deploy"

on:
  push:
    branches:
      - main
      - beta
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
          check-latest: true

      - name: Download dependencies
        run: go mod download

      - name: Start Test Database Container
        run: docker-compose -f docker-compose-unittest.yaml up -d

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test  -v -coverpkg ./internal/... -coverprofile coverage.out -covermode count ./internal/...
          go tool cover -func="./coverage.out"

  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    outputs:
      BRANCH: ${{ steps.branch.outputs.BRANCH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set branch
        id: branch
        run: |
          echo "::set-output name=BRANCH::${GITHUB_REF#refs/heads/}"

      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max