name: "Build and Deploy"

on:
  push:
    branches:
      - main
      - beta
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Start Test Database Container
        run: docker-compose -f docker-compose-unittest.yaml up -d

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test  -v -coverpkg ./internal/... -coverprofile coverage.out -covermode count ./internal/...
          go tool cover -func="./coverage.out"

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: test