name: "Pull request: Run unit test"

on:
  pull_request:
    branches:
      - main
      - beta
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Start Test Database Container
        run: docker-compose -f docker-compose-unittest.yaml up -d

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test  -v -coverpkg ./src/internal/... -coverprofile coverage.out -covermode count ./src/internal/...
          go tool cover -func="./coverage.out"
